
# Theme Settings
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

remote_theme: VSecDK/minimal-mistakes-theme
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "IamDevOps"
title_separator          : "-"
subtitle                 : DevOps Community
name                     : "IamDevOps"
email                    : ""
description: >- # this means to ignore newlines until "baseurl:"

twitter_username: IamDevOps
github_username: IamDevOps
search: true

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Copenhagen

include:
  - _pages
  - .well-known

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/iamDevOps"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/iamDevOps"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "#"

# Set Theme Defaults

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# Use Liquid Archives for categories/tags

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
